
export const CHANGE_DIFFICULTY='CHANGE_DIFFICULTY'
export const CHANGE_TYPE='CHANGE_TYPE'
export const CHANGE_AMOUNT='CHANGE_AMOUNT'
export const CHANGE_SCORE='CHANGE_SCORE'
export const RANDOM_QUESTION='RANDOM_QUESTION'
export const CHOICE_ANSWER='CHOICE_ANSWER'